export const BUILTIN_CAPABILITY_DOMAINS = [
  "application_control",
  "browser_control",
  "window_management",
  "clipboard",
  "keyboard",
  "mouse",
  "touch_input",
  "display",
  "audio",
  "media_playback",
  "camera",
  "microphone",
  "notifications",
  "storage",
  "filesystem",
  "downloads",
  "networking",
  "bluetooth",
  "wifi",
  "location",
  "calendar",
  "contacts",
  "messages",
  "phone_calls",
  "biometrics",
  "authentication",
  "battery",
  "power_management",
  "sensors",
  "device_information",
  "printing",
  "accessibility",
  "screen_capture",
  "process_management",
  "background_services",
  "smart_home",
  "automation",
  "ai_providers",
  "cloud_storage",
  "security",
] as const;

export type BuiltinCapabilityDomain = (typeof BUILTIN_CAPABILITY_DOMAINS)[number];
