import type { CapabilityDescriptor, CapabilityManager } from "@ryper/platform-capability";

const VERSION = "0.1.0";

/**
 * The `CapabilityDescriptor` for every domain the Windows Platform Agent
 * implements. Registering these with a `CapabilityManager` is what lets
 * `CapabilityManager.invoke()` run its permission-check/parameter-
 * validation pipeline before ever reaching `WindowsAdapter.invoke()` —
 * an unregistered domain still works (per PCL's design, a descriptor is
 * optional), it just skips that pipeline. `requiredCapability` is left
 * unset for domains with no matching entry in `@ryper/security`'s
 * `Capability` union (the same "partial by design" situation
 * `docs/adr/0006` documents for the Planner's `TASK_TYPE_TO_DOMAIN`) —
 * see `README.md`'s "Honest Limitations" section.
 */
export const WINDOWS_CAPABILITY_DESCRIPTORS: readonly CapabilityDescriptor[] = [
  {
    domain: "application_control",
    name: "Application Control",
    description: "Launch, close, restart, and enumerate Windows applications; open URLs and files.",
    version: VERSION,
    requiredCapability: "automation.execute",
    operationCapabilities: {
      enumerate_installed: "automation.read",
      enumerate_running: "automation.read",
      list_browsers: "automation.read",
      launch: "automation.execute",
      close: "automation.execute",
      restart: "automation.execute",
      open_url: "automation.execute",
      open_file: "automation.execute",
      open_folder: "automation.execute",
      launch_browser: "automation.execute",
      smart_open: "automation.execute",
    },
  },
  {
    domain: "window_management",
    name: "Window Management",
    description: "Move, resize, snap, center, focus, and enumerate windows; read window metadata.",
    version: VERSION,
    requiredCapability: "automation.execute",
    operationCapabilities: {
      enumerate: "automation.read",
      get_active: "automation.read",
      get_metadata: "automation.read",
      focus: "automation.execute",
      foreground: "automation.execute",
      minimize: "automation.execute",
      maximize: "automation.execute",
      restore: "automation.execute",
      snap: "automation.execute",
      center: "automation.execute",
      move: "automation.execute",
      resize: "automation.execute",
      switch_active: "automation.execute",
    },
  },
  {
    domain: "clipboard",
    name: "Clipboard",
    description: "Read/write the Windows clipboard, read its history, and monitor for changes.",
    version: VERSION,
  },
  {
    domain: "notifications",
    name: "Notifications",
    description: "Show, update, and dismiss native Windows toast notifications.",
    version: VERSION,
    requiredCapability: "automation.execute",
    operationCapabilities: {
      list: "automation.read",
      list_notifications: "automation.read",
      get: "automation.read",
      get_notification: "automation.read",
      inspect_notification: "automation.read",
      show: "automation.execute",
      show_notification: "automation.execute",
      update: "automation.execute",
      update_notification: "automation.execute",
      dismiss: "automation.execute",
      dismiss_notification: "automation.execute",
    },
  },
  {
    domain: "system_tray",
    name: "System Tray",
    description: "Inspect and manage the Windows system tray icon, tooltip, and menu state.",
    version: VERSION,
    requiredCapability: "automation.execute",
    operationCapabilities: {
      get_status: "automation.read",
      get_state: "automation.read",
      inspect: "automation.read",
      update_tooltip: "automation.execute",
      update_tray: "automation.execute",
      set_visibility: "automation.execute",
      destroy: "automation.execute",
    },
  },
  {
    domain: "audio",
    name: "Audio",
    description:
      "Volume, mute, default device selection, device enumeration, and media playback controls.",
    version: VERSION,
    requiredCapability: "automation.execute",
    operationCapabilities: {
      list_devices: "automation.read",
      get_volume: "automation.read",
      get_mute: "automation.read",
      get_media_state: "automation.read",
      set_volume: "automation.execute",
      set_mute: "automation.execute",
      set_default_device: "automation.execute",
      media_control: "automation.execute",
    },
  },
  {
    domain: "display",
    name: "Display",
    description: "Enumerate displays and read their configuration.",
    version: VERSION,
    requiredCapability: "automation.execute",
    operationCapabilities: {
      list: "automation.read",
      get_primary: "automation.read",
    },
  },
  {
    domain: "filesystem",
    name: "Filesystem",
    description:
      "Browse, read, write, copy, move, rename, delete, create, and search files and folders.",
    version: VERSION,
    requiredCapability: "filesystem.write",
    operationCapabilities: {
      list: "filesystem.read",
      list_directory: "filesystem.read",
      read: "filesystem.read",
      search: "filesystem.read",
      recent: "filesystem.read",
      well_known_folder: "filesystem.read",
      write: "filesystem.write",
      copy: "filesystem.write",
      move: "filesystem.write",
      rename: "filesystem.write",
      delete: "filesystem.write",
      create_folder: "filesystem.write",
    },
  },
  {
    domain: "device_information",
    name: "Device Information",
    description:
      "CPU/GPU/RAM/storage/battery/Windows version/installed applications/network status.",
    version: VERSION,
    requiredCapability: "automation.execute",
    operationCapabilities: {
      get_system_info: "automation.read",
      get_windows_version: "automation.read",
      list_devices: "automation.read",
      list_network_adapters: "automation.read",
      list_installed_applications: "automation.read",
    },
  },
  {
    domain: "process_management",
    name: "Process Management",
    description: "Enumerate, start, and (with confirmation) terminate OS processes.",
    version: VERSION,
    requiredCapability: "automation.execute",
    operationCapabilities: {
      list: "automation.read",
      get: "automation.read",
      kill: "automation.execute",
      restart: "automation.execute",
      start: "automation.execute",
    },
  },
  {
    domain: "background_services",
    name: "Windows Services",
    description: "Enumerate and control Windows services (Service Control Manager).",
    version: VERSION,
    requiredCapability: "automation.execute",
    operationCapabilities: {
      list: "automation.read",
      list_services: "automation.read",
      status: "automation.read",
      get: "automation.read",
      get_service: "automation.read",
      inspect_service: "automation.read",
      get_service_status: "automation.read",
      start: "automation.execute",
      start_service: "automation.execute",
      stop: "automation.execute",
      stop_service: "automation.execute",
      restart: "automation.execute",
      restart_service: "automation.execute",
      pause: "automation.execute",
      pause_service: "automation.execute",
      resume: "automation.execute",
      resume_service: "automation.execute",
      delete: "automation.execute",
      delete_service: "automation.execute",
      remove_service: "automation.execute",
      list_scheduled_tasks: "automation.read",
      get_scheduled_task: "automation.read",
      inspect_scheduled_task: "automation.read",
      run_scheduled_task: "automation.execute",
      enable_scheduled_task: "automation.execute",
      disable_scheduled_task: "automation.execute",
      create_scheduled_task: "automation.execute",
      delete_scheduled_task: "automation.execute",
    },
  },
  {
    domain: "task_scheduler",
    name: "Windows Task Scheduler",
    description: "Enumerate, inspect, run, enable, disable, create, and delete scheduled tasks.",
    version: VERSION,
    requiredCapability: "automation.execute",
    operationCapabilities: {
      list: "automation.read",
      list_scheduled_tasks: "automation.read",
      get: "automation.read",
      get_scheduled_task: "automation.read",
      inspect_scheduled_task: "automation.read",
      run: "automation.execute",
      run_scheduled_task: "automation.execute",
      enable: "automation.execute",
      enable_scheduled_task: "automation.execute",
      disable: "automation.execute",
      disable_scheduled_task: "automation.execute",
      create: "automation.execute",
      create_scheduled_task: "automation.execute",
      register_scheduled_task: "automation.execute",
      delete: "automation.execute",
      delete_scheduled_task: "automation.execute",
      unregister_scheduled_task: "automation.execute",
    },
  },
  {
    domain: "registry",
    name: "Windows Registry",
    description:
      "Read, list, search, inspect, create, modify, and delete Windows registry keys and values.",
    version: VERSION,
    requiredCapability: "automation.execute",
    operationCapabilities: {
      read: "automation.read",
      get_registry_value: "automation.read",
      list: "automation.read",
      list_registry_values: "automation.read",
      inspect_key: "automation.read",
      inspect_registry_key: "automation.read",
      write: "automation.execute",
      set_registry_value: "automation.execute",
      delete_value: "automation.execute",
      delete_registry_value: "automation.execute",
      delete_key: "automation.execute",
      delete_registry_key: "automation.execute",
    },
  },
  {
    domain: "power_management",
    name: "Power Management",
    description:
      "System power state, battery status, power plan, lock, sleep, hibernate, shutdown, restart, sign out, and cancel shutdown.",
    version: VERSION,
    requiredCapability: "automation.execute",
    operationCapabilities: {
      get_power_status: "automation.read",
      get_battery_status: "automation.read",
      get_power_plan: "automation.read",
      get_system_power_state: "automation.read",
      lock: "automation.execute",
      sleep: "automation.execute",
      hibernate: "automation.execute",
      shutdown: "automation.execute",
      restart: "automation.execute",
      sign_out: "automation.execute",
      cancel_shutdown: "automation.execute",
    },
  },
  {
    domain: "networking",
    name: "Windows Networking",
    description:
      "Windows network adapters, IP configuration, DNS configuration, and network interface controls.",
    version: VERSION,
    requiredCapability: "automation.execute",
    operationCapabilities: {
      list_adapters: "automation.read",
      list_network_adapters: "automation.read",
      get_adapter: "automation.read",
      get_network_configuration: "automation.read",
      get_ip_configuration: "automation.read",
      get_dns_configuration: "automation.read",
      get_network_status: "automation.read",
      get_active_adapter: "automation.read",
      inspect_interface: "automation.read",
      enable_adapter: "automation.execute",
      enable_network_adapter: "automation.execute",
      disable_adapter: "automation.execute",
      disable_network_adapter: "automation.execute",
      set_dhcp: "automation.execute",
      set_static_ip: "automation.execute",
      set_dns: "automation.execute",
      set_network_profile: "automation.execute",
      renew_dhcp: "automation.execute",
      release_dhcp: "automation.execute",
      reset_adapter: "automation.execute",
    },
  },
  {
    domain: "security",
    name: "Windows Security",
    description: "Query and (via explicit user confirmation) request UAC elevation.",
    version: VERSION,
  },
  {
    domain: "diagnostics",
    name: "Windows Agent Diagnostics",
    description: "Structured logs, capability diagnostics, error reports, and health checks.",
    version: VERSION,
  },
  {
    domain: "performance_monitoring",
    name: "Windows Performance Monitoring",
    description: "CPU/memory/disk-I/O sampling and rolling performance summaries.",
    version: VERSION,
  },
];

/** Registers every descriptor above with a `CapabilityManager`, skipping ones already registered (idempotent). */
export function registerWindowsCapabilityDescriptors(manager: CapabilityManager): void {
  for (const descriptor of WINDOWS_CAPABILITY_DESCRIPTORS) {
    if (manager.registry.has(descriptor.domain)) continue;
    manager.registerCapability(descriptor);
  }
}
